server:
  port: 8081
  servlet:
    context-path: ${SERVICE_PATH:/}
spring:
  application:
    name: FPRO
    time_zone: GMT+7
  profiles:
    active: ${ENV:dev}
  thymeleaf:
    cache: true
  jackson:
    serialization:
      indent-output: true
      fail-on-empty-beans: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://ls-4858f5b1ba4c5b862804146ab97d20fce7e7f6c7.cjlmnrhfxrnx.ap-southeast-1.rds.amazonaws.com:3306/fpro
    username: dbmasteruser
    password: $-_$0f2uX+z37fg3aXw_2pAs0unO%nkk
    #    url: jdbc:mysql://localhost:3306/mikepro
    #    username: sa
    #    password: 123123
    hikari:
      auto-commit: false
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: amc.building.mb@gmail.com
    password: 123456aA@
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  messages:
    encoding: 'UTF-8'
    use-code-as-default-message: true
    basename: i18n/labels
    cache-duration: 60    # 60 second,
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    embedded: true
    timeout: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:http://localhost:8081/api/certificate/.well-known/jwks.json}
security:
  authentication:
    jwt:
      key-store: mbamc.jks
      key-store-password: 5tgbNHY^7ujm
      key-alias: viz
      access-token-expires-in: 1h
      refresh-token-expires-in: 30d
      email-token-expires-in: 10m

      base64-secret: 'LNRP5b4+y9LUC3oV9WuGIf4GYT8GDYVIlHCYhywX3edfVKMrahN842YmCEVo2OX8Rs2G/eoGgKy/+/PvhT1Q4Id9pBMYdjcwJP6OyTcSUnO/tw65I/CwtYQy6uzJ+DBVkAwLoh+yPCvJym7lbVipcaD7me1BiDLp0NCfNYaetRzOxOxFcA4E67lpIHrPsb97C/SuiQL+cre7UXfFHJZxGR1tOM2IKQytUe0Q11rkPRggVTvIOfTRPeBAhvhjRLxPxpxy3Xe8LAUpdthKtKf7yFUHL+jqpwQ9cvILCLuH9sRVn6szBTrrvxMsmY79o2o8ZiGIeuDMBt4ahVdvavWt6g=='
      # Token is valid 1 day
      token-duration: 1
      # Token is valid 30 days
      token-remember-me-duration: 30
      #refresh token duration (days)
      refesh-token-duration: 30
      #other data duration (minute)
      data-duration: 5
      #csrf-token-duration (second)
      csrf-token-duration: 30
    cookie:
      domain-name:
      enable-ssl: false
      http-only: true
      path: '/'
      sameSite: 'Strict'
  cache:
      url-patterns: '/i18n/*,/content/*,/app/*'
      # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
      allowed-origins: 'http://localhost:4200'
      allowed-methods: 'GET,POST,OPTIONS'
      allowed-headers: '*'
      exposed-headers: 'Authorization,Link,X-Total-Count,X-Action-Message,X-Action-Params'
      allow-credentials: true
      max-age: 1800

validation:
  password-regex: ^(?=.*[a-z])(?=.*[A-Z]).{8,}$ #password ?t nh?t 8 k? t? , 1 ch? th??ng, 1 ch? hoa .. advance ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\S+$).{8,}$
  username-regex: '^[a-zA-Z0-9]([._](?![._])|[a-zA-Z0-9]){1,72}[a-zA-Z0-9]$' #ky tu so + chu , k? t? (. _), do dai tu 3 den 75
  email-regex: '^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,35})$' #email kh?ng qu? 100 k? t?
  phone-number-regex: '^((\\s){0,}((\\+84-?)|0))((9|8|7|3|5|4|2)[0-9]{8,9}(\\s){0,})$'
  coordinate-regex: '^(-?\d+(\.\d+)?),\s*(-?\d+(\.\d+)?)$'
  phone-number-min-length: 4
  phone-number-max-length: 11
  fullname-min-length: 2
  fullname-max-length: 200
  username-min-length: 3
  username-max-length: 75
  password-min-length: 8
  password-max-length: 50
  email-min-length: 4
  email-max-length: 100
  name-max-length: 255
  code-min-length: 2
  code-max-length: 50
  address-max-length: 255
  description-max-length: 255
  int-number-max-length: 10

app:
  iam:
    deep-link-reset-password: dark.vn/reset-password
    domain: http://localhost:8081